### ISSUE TITLE
How do I install and use it

### ISSUE THREAD

**Issue by coldiceh** [twt-tec/Silent-Writing-Master#1]

**Comment by edge-bird** [comment]
oh, maybe you need to install this code if you need, then install the data(words and expressions) which you need! Just I think maybe you need to do it then you can learn your English words better! Or, you can ask the team "twt-tec", send email to them for some help, By the way, you can get the solution about this problem, as for as I know, someone like you need to get my idea,too, I hope they can watch this comment and get the help from me. In addtion, I hope you can solve this problem just now, but I can't solve this problem completely because I am not a member of  their team. If possible, I do hope I can join them because this is a good team.

**Comment by Acfboy** [comment]
@coldiceh @edge-bird 

你们俩搞什么？？直接编译运行，然后输入需要的单元编号就可以了！

**Comment by coldiceh** [comment]
![](https://cdn.luogu.com.cn/upload/image_hosting/9t4az629.png)

**Comment by coldiceh** [comment]
> @coldiceh @edge-bird
> 
> 你们俩搞什么？？直接编译运行，然后输入需要的单元编号就可以了！

https://cdn.luogu.com.cn/upload/image_hosting/9t4az629.png how can i solve this prob?

**Comment by edge-bird** [comment]
Ok, thank you sir! I think I may know how to solve my stupid problem now, and can you tell me more details about your projects "Slient Writing Master"? In addtion, I think I need a installation package about this tool? Maybe I should call it a software,I do hope you can upload more data about words for this tool. At last, thank for you Contribution!
